conf-core/src/main/java/org/openepics/discs/conf/ui/DevicesController.java
/*
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 *
 * This file is part of Controls Configuration Database.
 *
 * Controls Configuration Database is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of the License,
 * or any newer version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package org.openepics.discs.conf.ui;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import javax.annotation.PostConstruct;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.openepics.discs.conf.dl.annotations.DevicesLoader;
import org.openepics.discs.conf.dl.common.DataLoader;
import org.openepics.discs.conf.dl.common.DataLoaderResult;
import org.openepics.discs.conf.ejb.ComptypeEJB;
import org.openepics.discs.conf.ejb.DeviceEJB;
import org.openepics.discs.conf.ent.ComponentType;
import org.openepics.discs.conf.ent.Device;
import org.openepics.discs.conf.ent.DevicePropertyValue;
import org.openepics.discs.conf.export.ExportTable;
import org.openepics.discs.conf.ui.common.AbstractExcelSingleFileImportUI;
import org.openepics.discs.conf.ui.common.DataLoaderHandler;
import org.openepics.discs.conf.ui.common.ExcelSingleFileImportUIHandlers;
import org.openepics.discs.conf.ui.common.UIException;
import org.openepics.discs.conf.ui.export.ExportSimpleTableDialog;
import org.openepics.discs.conf.ui.export.SimpleTableExporter;
import org.openepics.discs.conf.ui.lazymodels.CCDBLazyModel;
import org.openepics.discs.conf.ui.lazymodels.DeviceLazyModel;
import org.openepics.discs.conf.ui.util.Action;
import org.openepics.discs.conf.ui.util.Entity;
import org.openepics.discs.conf.ui.util.Summary;
import org.openepics.discs.conf.ui.util.UiUtility;
import org.openepics.discs.conf.util.BatchIterator;
import org.openepics.discs.conf.util.BatchSaveStage;
import org.openepics.discs.conf.util.ImportFileStatistics;
import org.openepics.discs.conf.util.Utility;
import org.openepics.discs.conf.views.DeviceView;
import org.primefaces.context.RequestContext;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.LazyDataModel;

import com.google.common.base.Preconditions;
import com.google.common.base.Strings;
import com.google.common.collect.Lists;

/**
 * Controller bean for manipulation of {@link Device} attributes
 *
 * @author <a href="mailto:miha.vitorovic@cosylab.com">Miha Vitorovič</a>
 *
 */
@Named
@ViewScoped
public class DevicesController implements SimpleTableExporter, ExcelSingleFileImportUIHandlers, Serializable {
    private static final long serialVersionUID = -2881746639197321061L;

    private static final Logger LOGGER = Logger.getLogger(DevicesController.class.getCanonicalName());
    private static final String CRLF = "\r\n";

    @Inject private DataLoaderHandler dataLoaderHandler;
    @Inject @DevicesLoader private DataLoader devicesDataLoader;
    @Inject private ComptypeEJB componentTypesEJB;
    @Inject private DeviceEJB deviceEJB;
    @Inject private DeviceAttributesController deviceAttributesController;

    private Device device;

    private CCDBLazyModel<DeviceView> lazyModel;

    private List<DeviceView> selectedDevices;
    private List<DeviceView> usedDevices;
    private List<DeviceView> filteredDialogDevices;

    // Add/Edit device dialog
    private ComponentType selectedComponentType;
    private List<ComponentType> availableDeviceTypes;
    private String serialNumber;
    private boolean isDeviceBeingEdited;

    //---- batch device creation
    private boolean isBatchCreation;
    private int batchStartIndex;
    private int batchEndIndex;
    private int batchLeadingZeros;
    private String batchSerialConflicts;
    private BatchSaveStage batchSaveStage;
    private boolean batchSkipExisting;

    private transient ExportSimpleTableDialog simpleTableExporterDialog;

    private transient ExcelSingleFileImportUI excelSingleFileImportUI;

    private class ExcelSingleFileImportUI extends AbstractExcelSingleFileImportUI {
        /** Construct the file import UI for the device data loader. */
        public ExcelSingleFileImportUI() {
            super.init();
        }

        @Override
        public void setDataLoader() {
            dataLoader = devicesDataLoader;
        }

        @Override
        public void doImport() {
            try (InputStream inputStream = new ByteArrayInputStream(importData)) {
                setLoaderResult(dataLoaderHandler.loadData(inputStream, devicesDataLoader));
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }

    private class ExportSimpleDeviceTableDialog extends ExportSimpleTableDialog {
        @Override
        protected String getTableName() {
            return "Devices";
        }

        @Override
        protected String getFileName() {
            return "ccdb_devices";
        }

        @Override
        protected void addHeaderRow(ExportTable exportTable) {
            exportTable.addHeaderRow("Operation", "Type", "Inventory ID", "Property Name", "Property Value",
                    "Installed In", "Installation Timestamp");
        }

        @Override
        protected void addData(ExportTable exportTable) {
            final List<DeviceView> exportData = lazyModel.load(0, Integer.MAX_VALUE,
                                    lazyModel.getSortField(), lazyModel.getSortOrder(), lazyModel.getFilters());
            for (final DeviceView deviceInstance : exportData) {
                exportTable.addDataRow(DataLoader.CMD_UPDATE_DEVICE,
                        deviceInstance.getDevice().getComponentType().getName(), deviceInstance.getInventoryId(),
                        null, null,
                        "-".equals(deviceInstance.getInstalledIn()) ? null : deviceInstance.getInstalledIn(),
                        deviceInstance.getInstallationTimestamp());
                for (final DevicePropertyValue pv : deviceInstance.getDevice().getDevicePropertyList()) {
                    exportTable.addDataRow(DataLoader.CMD_UPDATE_PROPERTY, null, deviceInstance.getInventoryId(),
                            pv.getProperty().getName(), pv.getPropValue());
                }
            }
        }

        @Override
        protected String getExcelTemplatePath() {
            return "/resources/templates/ccdb_devices.xlsx";
        }

        @Override
        protected int getExcelDataStartRow() {
            return 10;
        }
    }

    public DevicesController() {}

    /** Java EE post construct life-cycle method. */
    @PostConstruct
    public void init() {
        final String deviceIdStr = ((HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().
                getRequest()).getParameter("id");

        try {
            excelSingleFileImportUI = new ExcelSingleFileImportUI();
            simpleTableExporterDialog = new ExportSimpleDeviceTableDialog();
            availableDeviceTypes = componentTypesEJB.findAll();
            lazyModel = new DeviceLazyModel(deviceEJB);
            if (!Strings.isNullOrEmpty(deviceIdStr)) {
                final long deviceId = Long.valueOf(deviceIdStr);
                final Device device = deviceEJB.findById(deviceId);
                if (device != null) {
                    RequestContext.getCurrentInstance().execute("CCDB.config.jumpToElementOnLoad = true;"
                            + "selectEntityInTable(" + deviceId + ", 'devicesTableVar');");
                }
            }
        } catch (NumberFormatException e) {
            // just log
            LOGGER.log(Level.WARNING, "URL contained strange unit ID: " + deviceIdStr);
        } catch(Exception e) {
            throw new UIException("Device type display initialization fialed: " + e.getMessage(), e);
        }
    }

    /** @see org.openepics.discs.conf.ui.common.ExcelImportUIHandlers#doImport() */
    @Override
    public void doImport() {
        excelSingleFileImportUI.doImport();
        deviceAttributesController.clearRelatedAttributeInformation();
    }

    /** @see org.openepics.discs.conf.ui.common.ExcelImportUIHandlers#prepareImportPopup() */
    @Override
    public void prepareImportPopup() {
        excelSingleFileImportUI.prepareImportPopup();
    }

    /** @see org.openepics.discs.conf.ui.common.ExcelImportUIHandlers#setDataLoader() */
    @Override
    public void setDataLoader() {
        excelSingleFileImportUI.setDataLoader();
    }

    /** @see org.openepics.discs.conf.ui.common.ExcelImportUIHandlers#getLoaderResult() */
    @Override
    public DataLoaderResult getLoaderResult() {
        return excelSingleFileImportUI.getLoaderResult();
    }

    /**
     * @see org.openepics.discs.conf.ui.common.ExcelSingleFileImportUIHandlers#handleImportFileUpload(FileUploadEvent)
     */
    @Override
    public void handleImportFileUpload(FileUploadEvent event) {
        excelSingleFileImportUI.handleImportFileUpload(event);
    }

conf-core/src/main/webapp/loaders/single-file-DL.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets" 
                xmlns:p="http://primefaces.org/ui" 
                xmlns:f="http://java.sun.com/jsf/core" 
                xmlns:h="http://java.sun.com/jsf/html">

    <h:form id="#{formId}" enctype="multipart/form-data">
        <p:dialog widgetVar="#{widgetName}" modal="true" resizable="false" width="35%" closeOnEscape="true">
            <f:facet name="header">
                <h:outputText value="#{dialogTitle}" />
            </f:facet>
            <h:panelGroup id="grp" layout="block">
                <h:panelGroup rendered="#{controller.excelImportFileName == null}" layout="block" 
                    style="padding: 0 0 7px 0">Please choose an Excel file (*.xlsx) to import data from.</h:panelGroup>
                <p:fileUpload id="singleFileDLUploadCtl" fileUploadListener="#{controller.handleImportFileUpload}" 
                    update="grp importStatsDialog" mode="advanced" auto="true" fileLimit="1" 
                    dragDropSupport="true" allowTypes="/(\.|\/)(xlsx)$/" oncomplete="PF('importStatsDialog').show();"
                    rendered="#{controller.excelImportFileName == null}" />
                <h:outputText value="#{controller.excelImportFileName}" />
                <p:separator />
                <p:commandButton value="Cancel" styleClass="dialogButton" onclick="PF('#{widgetName}').hide();" 
                    icon="ui-icon-close" />
                <p:commandButton value="Import" styleClass="dialogButton defaultCommand" id="importButton" 
                    update=":menuform :#{formId}" oncomplete="PF('#{widgetName}').hide();PF('statusDialog').hide();" 
                    action="#{controller.doImport()}" disabled="#{controller.excelImportFileName == null}" 
                    onclick="PF('statusDialog').show()" icon="ui-icon-arrowthickstop-1-n" />
            </h:panelGroup>
            
            <p:defaultCommand target="importButton" />
        </p:dialog>

        <p:dialog id="importStatsDialog" widgetVar="importStatsDialog" modal="true" resizable="false">
            <f:facet name="header">
                <h:outputText value="File uploaded" />
            </f:facet>
            <p:panelGrid style="margin-bottom: 1em;" styleClass="noBorders">
                <p:row>
                    <p:column styleClass="alignRight">
                        <h:outputText value="Data rows:" />
                    </p:column>
                    <p:column style="width: 5em;">
                        <h:outputText value="#{controller.importFileStatistics.dataRows}" />
                    </p:column>
                </p:row>

                <p:row>
                    <p:column styleClass="alignRight">
                        <h:outputText value="Create rows:" />
                    </p:column>
                    <p:column style="width: 5em;">
                        <h:outputText value="#{controller.importFileStatistics.createRows}" />
                    </p:column>
                </p:row>

                <p:row>
                    <p:column styleClass="alignRight">
                        <h:outputText value="Update rows:" />
                    </p:column>
                    <p:column style="width: 5em;">
                        <h:outputText value="#{controller.importFileStatistics.updateRows}" />
                    </p:column>
                </p:row>

                <p:row>
                    <p:column styleClass="alignRight">
                        <h:outputText value="Delete rows:" />
                    </p:column>
                    <p:column style="width: 5em;">
                        <h:outputText value="#{controller.importFileStatistics.deleteRows}" />
                    </p:column>
                </p:row>

                <p:row>
                    <p:column styleClass="alignRight">
                        <h:outputText value="Skipped rows:" />
                    </p:column>
                    <p:column style="width: 5em;">
                        <h:outputText 
                            value="#{controller.importFileStatistics.dataRows - controller.importFileStatistics.importRows}" />
                    </p:column>
                </p:row>
            </p:panelGrid>
            <p:commandButton value="Close" type="button" styleClass="dialogButton" title="Close" 
                    onclick="PF('importStatsDialog').hide();" icon="ui-icon-close" />
        </p:dialog>

        <p:dialog id="resultDialog" widgetVar="resultDialog" modal="true" style="max-width: 90%; max-height: 600px;" 
                visible="#{controller.excelImportFileName != null and controller.loaderResult != null}" resizable="false" 
                closable="false">  
            <f:facet name="header">
                <h:outputText style="#{controller.loaderResult.error ? 'color: red !important;' : ''}" 
                    value="#{!controller.loaderResult.error ? 'Import Successful' : 'Error in Import Spreadsheet'}" />
            </f:facet>

            <p:panel styleClass="noBorders para">
                <h:panelGroup rendered="#{controller.loaderResult.error}" layout="block">
                    Data cannot be imported since there are some errors in the spreadsheet. 
                    Please correct the errors and try the import again.
                </h:panelGroup>
                <h:panelGroup rendered="#{!controller.loaderResult.error}" layout="block">
                    Data was successfully imported.
                </h:panelGroup>
            </p:panel>

            <p:dataTable value="#{controller.loaderResult.messages}" var="errorRow" scrollable="true" scrollHeight="180" 
                    filteredValue="#{controller.loaderResult.filteredMessages}"
                    style="max-width: 100%; margin-bottom: 1em; width: 58em;" rendered="#{controller.loaderResult.error}">
                <p:column headerText="Row" width="15%" filterBy="#{errorRow.row}" filterMatchMode="contains" 
                        sortBy="#{errorRow.row}">
                    <h:outputText value="#{errorRow.row}" styleClass="#{errorRow.error ? '' : 'messageWarning'}" />
                </p:column>
                <p:column headerText="Column" width="15%" filterBy="#{errorRow.column}" filterMatchMode="contains" 
                        sortBy="#{errorRow.column}">
                    <h:outputText value="#{errorRow.column}" styleClass="#{errorRow.error ? '' : 'messageWarning'}" />
                </p:column>
                <p:column headerText="Value" width="15%" filterBy="#{errorRow.value}" filterMatchMode="contains" 
                        sortBy="#{errorRow.value}">
                    <h:outputText value="#{empty errorRow.value ? '&lt;undefined&gt;' : errorRow.value}"
                         styleClass="#{errorRow.error ? '' : 'messageWarning'}" />
                </p:column>
                <p:column headerText="Error" width="55%" filterBy="#{errorRow.message.toString()}" 
                        filterMatchMode="contains" sortBy="#{errorRow.message.toString()}">
                    <h:outputText value="#{errorRow.message.toString()}" styleClass="#{errorRow.error ? '' : 'messageWarning'}" />
                </p:column>
            </p:dataTable>

            <p:panelGrid style="margin-bottom: 1em;" styleClass="noBorders" 
                    rendered="#{!controller.loaderResult.error}">
                <p:row>
                    <p:column styleClass="alignRight">
                        <h:outputText value="Data rows:" />
                    </p:column>
                    <p:column style="width: 5em;">
                        <h:outputText value="#{controller.importFileStatistics.dataRows}" />
                    </p:column>
                </p:row>

                <p:row>
                    <p:column styleClass="alignRight">
                        <h:outputText value="Create rows:" />
                    </p:column>
                    <p:column style="width: 5em;">
                        <h:outputText value="#{controller.importFileStatistics.createRows}" />
                    </p:column>
                </p:row>

                <p:row>
                    <p:column styleClass="alignRight">
                        <h:outputText value="Update rows:" />
                    </p:column>
                    <p:column style="width: 5em;">
                        <h:outputText value="#{controller.importFileStatistics.updateRows}" />
                    </p:column>
                </p:row>

                <p:row>
                    <p:column styleClass="alignRight">
                        <h:outputText value="Delete rows:" />
                    </p:column>
                    <p:column style="width: 5em;">
                        <h:outputText value="#{controller.importFileStatistics.deleteRows}" />
                    </p:column>
                </p:row>

                <p:row>
                    <p:column styleClass="alignRight">
                        <h:outputText value="Skipped rows:" />
                    </p:column>
                    <p:column style="width: 5em;">
                        <h:outputText 
                            value="#{controller.importFileStatistics.dataRows - controller.importFileStatistics.importRows}" />
                    </p:column>
                </p:row>
            </p:panelGrid>

            <p:commandButton value="Close" type="button" styleClass="dialogButton" onclick="PF('resultDialog').hide();" 
                    style="margin-top: 1ex;" icon="ui-icon-close" title="Close">
                <p:ajax disabled="#{not fn:endsWith(request.requestURL,'devices.xhtml')}" 
                    update=":devicesForm:devicesTable :devicesForm:attributesDataTable:attributesDataTable" 
                    oncomplete="PF('devicesTableVar').clearFilters();PF('attributesDataTable').clearFilters();" />
                <p:ajax disabled="#{not fn:endsWith(request.requestURL,'device-types.xhtml')}" 
                    update=":deviceTypesForm:deviceTypeTable :deviceTypesForm:attributesDataTable:attributesDataTable"
                    oncomplete="PF('deviceTypeTableVar').clearFilters();PF('attributesDataTable').clearFilters();" />
                <p:ajax disabled="#{not fn:endsWith(request.requestURL,'properties.xhtml')}" 
                    update=":propertiesForm:propertiesTable" oncomplete="PF('propertiesTableVar').clearFilters();" />
                <p:ajax disabled="#{not fn:endsWith(request.requestURL,'enums.xhtml')}" update=":enumsForm:enumsTable"
                    oncomplete="PF('enumsTableVar').clearFilters();" />
                <p:ajax disabled="#{not fn:endsWith(request.requestURL,'units.xhtml')}" update=":unitsForm:unitsTable"
                    oncomplete="PF('unitsTableVar').clearFilters();" />
                <p:ajax disabled="#{not fn:endsWith(request.requestURL,'home.xhtml')}" 
                    update=":hierarchies:hierarchyTabs :hierarchies:content:attributesDataTable:attributesDataTable 
                            :hierarchies:content:relationsTable :hierarchies:content:installationDetails" 
                    oncomplete="hierarchiesResizeAll();" />
            </p:commandButton>
            <p:commandButton id="exportButton" icon="ui-icon-disk" value="Export" title="Export" 
                styleClass="dialogButton" style="margin-top: 1ex;" oncomplete="PF('#{formId}_exportErrors').show();" 
                rendered="#{controller.loaderResult.error}" update=":#{formId}_exportErrorsForm:#{formId}_exportErrors" 
                actionListener="#{controller.simpleErrorTableExportDialog.prepareTableExportPopup}" />
        </p:dialog>
    </h:form>

    <ui:include src="/resources/dialogs/export-table.xhtml">
        <!-- the order has to be "widgetName" before "formId" -->
        <ui:param name="widgetName" value="#{formId}_exportErrors" />
        <ui:param name="formId" value="#{formId}_exportErrorsForm" />
        <ui:param name="dialogTitle" value="Export errors table" />
        <ui:param name="fileFormatSelection" value="#{controller.simpleErrorTableExportDialog.fileFormat}" />
        <ui:param name="includeHeader" value="#{controller.simpleErrorTableExportDialog.includeHeaderRow}" />
        <ui:param name="tableFile" value="#{controller.simpleErrorTableExportDialog.exportedTable}" />
    </ui:include>
</ui:composition>